# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d77b79e71136860baf34fde95874296fc6e46e352f21922550300c97355115797f9b088d1577319db35ab2dc9f07e15d00744e26b52dc8c33b68df8f660a7e

test:
  secret_key_base: 54b501ff1e4259ca96b3bdb07a581a2575d0be3710d20c5e620e429d1c52cbe03ff51e22e0d5677c50785ba708f256de4eb6f9d5e6a3d24eb178aebb3b54535e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
